eureka:
  instance:
    hostname: ${spring.application.name}
    instance-id: ${spring.application.name}_${random.int}:${server.port}
    preferIpAddress: false


spring:
  cloud:
    config:
      uri: http://localhost:11556/