server:
  port: 11553

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:11555/eureka/
  instance:
    hostname: service
    instance-id: ${spring.application.name}_${random.int}:${server.port}
    preferIpAddress: false