server:
  port: 11551

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka:11555/eureka/
  instance:
    hostname: security
    instance-id: ${spring.application.name}_${random.int}:${server.port}
    preferIpAddress: false

management:
  security:
    enabled: true

spring:
  resources:
    chain:
      enabled: true